name: Generate Profile Extras

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Generates the GitHub Profile Trophies
      - name: Generate GitHub Trophies
        uses: soulteary/github-profile-trophy-action@v1.0.0
        with:
          options: 'username=${{ github.repository_owner }}&theme=nord&no-bg=true&no-frame=true&column=-1&rank=SECRET,SSS,SS,S,AAA,AA,A,B'
          path: generated/github-trophies.svg 
          token: ${{ secrets.GITHUB_TOKEN }}

      # Generates the classic GitHub Readme Stats SVG
      - name: Generate GitHub Stats
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&include_all_commits=true&theme=shadow_green&hide_border=true
          path: generated/github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Generates the Streak Stats SVG
      - name: Generate Streak Stats
        # uses: muhammad-fiaz/github-readme-streak-stats@v1.0.1 # TODO: Switch back to this once they accept my PR is accepted
        uses: qhanson55/github-readme-streak-stats@feat/weekly-streak
        with:
          USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          THEME: shadow-green
          HIDE_BORDER: "true"
          WEEK_STREAK: "true"
          OUTPUT_PATH: generated/github-streak.svg

      - name: Push generated SVGs to branch
        uses: crazy-max/ghaction-github-pages@v4.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_branch: output-extras
          build_dir: generated
          keep_history: true