name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate 3D Profile SVG
      uses: yoshi389111/github-profile-3d-contrib@0.9.0
      env:
        GITHUB_TOKEN: ${{ secrets.PROFILE_README_TOKEN }}
        USERNAME: ${{ github.repository_owner }}

    - name: Push SVGs to branch
      uses: crazy-max/ghaction-github-pages@v3.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.PROFILE_README_TOKEN }}
      with:
        target_branch: output-3d-contrib
        build_dir: profile-3d-contrib